### ISSUE TITLE
Error: experimental Nix feature 'nix-command' is disabled

### ISSUE THREAD

**Issue by petabyteboy** [Mic92/tex2nix#3]
```
[pbb@mozarella:~/nyantec/doc]$ nix run -f https://github.com/Mic92/tex2nix/archive/main.tar.gz
[1 built, 29 copied (29.4 MiB), 5.4 MiB DL]

[pbb@mozarella:~/nyantec/doc]$ result

[pbb@mozarella:~/.../doc]$ tex2nix pandoc/default.latex
error: --- Error ------------------------------------------------------------------------------------ nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
Traceback (most recent call last):
  File "/nix/store/wnp6kx90fmv9rpzx1i8imyz5w93whxgh-tex2nix/bin/.tex2nix-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/wnp6kx90fmv9rpzx1i8imyz5w93whxgh-tex2nix/lib/python3.8/site-packages/tex2nix/__init__.py", line 92, in main
    packages = extract_dependencies(fileinput.input())
  File "/nix/store/wnp6kx90fmv9rpzx1i8imyz5w93whxgh-tex2nix/lib/python3.8/site-packages/tex2nix/__init__.py", line 86, in extract_dependencies
    all_packages = get_nix_packages()
  File "/nix/store/wnp6kx90fmv9rpzx1i8imyz5w93whxgh-tex2nix/lib/python3.8/site-packages/tex2nix/__init__.py", line 13, in get_nix_packages
    res = subprocess.run(
  File "/nix/store/m7080pw0ryjk0jhljp55rq1hd2qy8gki-python3-3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', 'nixpkgs#texlive', '--apply', 'builtins.attrNames']' returned non-zero exit status 1.

[pbb@mozarella:~/.../doc]$
```

This is caused by the program being wrapped to use nixFlakes and using the nix v2 `nix eval` command.

**Comment by petabyteboy** [comment]
I fixed it for my use case here: https://github.com/petabyteboy/tex2nix/commit/0613bb4f8c94697104fa033a13ca6bc79e876d79
However, there is probably a reason you used texlive from the nixpkgs flake in your setup. Probably should be possible to support both.

**Comment by Mic92** [comment]
Applied in https://github.com/Mic92/tex2nix/pull/4
